### ISSUE TITLE
Erro no icon header 

### ISSUE THREAD

**Issue by VagnerBellacosa** [fael-atom/instagram-login-page#1]
Olha meu camarada,

estive olhando o codigo fonte da sua pagina html e esta diferente do projeto no Github.

<link rel="icon" sizes="192x192" href="/images/instagram-favicon.ico">

para funcionar

<link rel="icon" sizes="192x192" href="/images/instagram-favicon.png">

Espero ter ajudado

**Comment by VagnerBellacosa** [comment]
De:
<
link rel="icon" sizes="192x192" href="/images/instagram-favicon.ico"
>

Para:

<
link rel="icon" sizes="192x192" href="/images/instagram-favicon.png"
>

**Comment by fael-atom** [comment]
Fala Vagner! Tudo joia? Então, acabei de ver a página aqui e realmente o código-fonte está desatualizado. Não compreendo o porquê disso. Estava dando uma pesquisada aqui e vi que pode ser um problema de fuso horário com o servidor do GitHub. Pode ser ainda algum problema com a configuração do meu GitHub Pages Se souber o motivo, manda aqui pra mim, por favor!

**Comment by VagnerBellacosa** [comment]
Amigo Rafael, eu nao sei, mas vou pesquisar e qdo descobrir te dou um
alo... vc viu no forke, deixei uns comentários para vc explorar
mais...

Vc pode incluir técnicas SEO no header, modulo de estatistica e
treinar uso de palavras chaves.

Qualquer coisa é so chamar. Fica bem e continuação de bom curso

Em 27/01/2022, Rafael ***@***.***> escreveu:
> Fala Vagner! Tudo joia? Então, acabei de ver a página aqui e realmente o
> código-fonte está desatualizado. Não compreendo o porquê disso. Estava dando
> uma pesquisada aqui e vi que pode ser um problema de fuso horário com o
> servidor do GitHub. Se souber o motivo, manda aqui pra mim!

>

>

> --

> Reply to this email directly or view it on GitHub:

> https://github.com/fael-atom/instagram-login-page/issues/1#issuecomment-1023781178

> You are receiving this because you authored the thread.

>

> Message ID: ***@***.***>


-- 
___________________________________________________________________________________


Visite Bellacosa Index Page:
*Bellacosa Index Page*
<https://bellacosa-index-page.negocio.site/website/bellacosa-index-page/>

*Visite meu blog fotos de viagens, videos de aventuras e muito mais.*
<http://eljefemidnightlunch.blogspot.com.br/>

*Youtube El Jefe MIdnight Lunch
<http://www.youtube.com/c/ElJefeMidnightLunch?sub_confirmation=1>   *

*http://eljefemidnightlunch.blogspot.com.br/*
<http://eljefemidnightlunch.blogspot.com.br/>

*Um Andarilho Visita Portugal*
<https://andarilhovisitaportugal.blogspot.com/2020/11/um-andarilho-e-suas-aventuras-venha.html>

**Comment by fael-atom** [comment]
Vagner, vi sim as suas sugestões! Foram ótimas! Qualquer hora vou te perturbar um pouquinho lá no LinkedIn para me dar umas dicas de como construir um contador haha vi que no seu blog tem um (dei uma explorada lá ontem kkk). Obrigado desde já por toda ajuda! 😁

**Comment by fael-atom** [comment]
> 

Fala, Vagner! Tudo joia?? 

Olha só, consegui descobrir o problema do favicon. Percebi, vendo outros códigos por aí, que a única coisa que faltava era um PONTO haha 

Então, bastava colocar um ponto na frente de `/images/instagram-favicon.png`, remetendo ao diretório atual. Confira no último commit do repositório. 

Desde já meus agradecimentos pela ajuda!!!

**Comment by VagnerBellacosa** [comment]
Legal meu amigo, #tmj

2022-03-08 18:07 GMT-03:00, Rafael Mota ***@***.***>:
> Closed #1.
>
> --
> Reply to this email directly or view it on GitHub:
> https://github.com/fael-atom/instagram-login-page/issues/1#event-6205374741
> You are receiving this because you authored the thread.
>
> Message ID:
> ***@***.***>


-- 
___________________________________________________________________________________


Visite Bellacosa Index Page:
*Bellacosa Index Page*
<https://bellacosa-index-page.negocio.site/website/bellacosa-index-page/>

*Visite meu blog fotos de viagens, videos de aventuras e muito mais.*
<http://eljefemidnightlunch.blogspot.com.br/>

*Youtube El Jefe MIdnight Lunch
<http://www.youtube.com/c/ElJefeMidnightLunch?sub_confirmation=1>   *

*http://eljefemidnightlunch.blogspot.com.br/*
<http://eljefemidnightlunch.blogspot.com.br/>

*Um Andarilho Visita Portugal*
<https://andarilhovisitaportugal.blogspot.com/2020/11/um-andarilho-e-suas-aventuras-venha.html>
